/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package chess

import chess.common.model.Game
import chess.common.model.players.BlackPlayer
import chess.common.model.players.WhitePlayer

fun main() {
    fancyPrintln("Welcome to the best game of Chess!")
    do {
        fancyPrintln("Input a player (white/black): ")
        val inputPlayer = readlnOrNull()
        if (checkExitGame(inputPlayer)) {
            fancyPrintln("exiting game :(")
            return
        }
        val correctInput = inputPlayer?.matches(Regex("^(white|black)$")) == true
        if (correctInput) {
            fancyPrintln("You will be playing as $inputPlayer")
            startGame(inputPlayer!!)
        } else {
            fancyPrintln("You didn't enter white or black. You entered: $inputPlayer. Please enter (white/black).")
        }
    } while (!correctInput)
}

fun startGame(player: String) {
    if (player == "white") {
        Game.startNewGame(
            pickedPlayer =
                WhitePlayer(
                    name = "white",
                    playerPoints = 0,
                ),
            otherPlayer =
                BlackPlayer(
                    name = "black",
                    playerPoints = 0,
                ),
        )
    } else {
        Game.startNewGame(
            pickedPlayer =
                BlackPlayer(
                    name = "black",
                    playerPoints = 0,
                ),
            otherPlayer =
                WhitePlayer(
                    name = "white",
                    playerPoints = 0,
                ),
        )
    }
}
